subprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://repo.grails.org/grails/restricted' }
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeGroupAndSubgroups('org.apache.grails')
                includeGroupAndSubgroups('org.apache.groovy')
            }
            mavenContent { snapshotsOnly() }
        }
    }
}

// Workaround needed for nexus publishing bug
// version and group must be specified in the root project
// https://github.com/gradle-nexus/publish-plugin/issues/310
version = projectVersion
group = 'org.grails.plugins'
subprojects {
    if (name == 'grails-logical-delete') {
        apply plugin: 'org.apache.grails.gradle.grails-publish'
    }
}
