subprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://repo.grails.org/grails/restricted' }
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeGroupAndSubgroups('org.apache.grails')
                includeGroupAndSubgroups('org.apache.groovy')
            }
            mavenContent { snapshotsOnly() }
        }
    }
}
